name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Get package version
        id: pkg
        run: echo "version=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_OUTPUT

      - name: Check if version is already published
        id: published
        run: |
          NPM_VIEW=$(npm view @jupiterone/jupiterone-mcp version || echo "none")
          echo "published_version=$NPM_VIEW" >> $GITHUB_OUTPUT

      - name: Publish to npm
        if: steps.pkg.outputs.version != steps.published.outputs.published_version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish --access public